#!/usr/bin/env php
<?php
/* Author: Romain Dal Maso <artefact2@gmail.com>
 *
 * This program is free software. It comes without any warranty, to the
 * extent permitted by applicable law. You can redistribute it and/or
 * modify it under the terms of the Do What The Fuck You Want To Public
 * License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

require __DIR__.'/inc.php';

if($argc !== 2 || !file_exists($argv[1])) {
	fprintf(STDERR, "Usage: %s <script>\n", $argv[0]);
	die(1);
}

$s = new State();

require $argv[1];

PrintCharacterEntries($s->char);
