#!/usr/bin/env php
<?php
/* Author: Romain Dal Maso <artefact2@gmail.com>
 *
 * This program is free software. It comes without any warranty, to the
 * extent permitted by applicable law. You can redistribute it and/or
 * modify it under the terms of the Do What The Fuck You Want To Public
 * License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

namespace HeroesOfLegend;

require __DIR__.'/inc/root.php';

$c = Character::NPC("Default Character");
$s = new State($c);

if($argc > 1) {
	/* Non-interactive mode */

	array_shift($argv);
	while($argv !== []) {
		$spec = array_shift($argv);
		printf("%20.20s: %3.3d\n", $spec, (new DiceRoller($spec))->roll($s));
	}
	
	return;
}

echo "Interactive mode. Use ^D to quit.", PHP_EOL;

$lhist = null;
readline_callback_handler_install("spec> ", function(?string $line) use(&$lhist, &$s) {
	if($line === null) die();
	$spec = trim($line);
	if($spec === '') return;
	
	if($lhist !== $spec) {
		readline_add_history($spec);
		$lhist = $spec;
	}

	if(!DiceRoller::validateSpec($spec)) {
		echo "Syntax error", PHP_EOL;
		return;
	}
	
	echo (new DiceRoller($spec))->roll($s), PHP_EOL;
});

while(true) {
	readline_callback_read_char();
}
