#!/usr/bin/env php
<?php
/* Author: Romain Dal Maso <artefact2@gmail.com>
 *
 * This program is free software. It comes without any warranty, to the
 * extent permitted by applicable law. You can redistribute it and/or
 * modify it under the terms of the Do What The Fuck You Want To Public
 * License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

namespace HeroesOfLegend;

require __DIR__.'/../inc/root.php';

if($argc !== 2) {
	fprintf(STDERR, "Usage: %s <dataname>\n", $argv[0]);
	die(1);
}

$data = json_decode(file_get_contents(__DIR__.'/data.json'), true);
assert(is_array($data['names']) && is_array($data['links']) && is_array($data['invokes']));

$childrenof = $argv[1];

printf("Children/Invokees of %s: %s\n", $childrenof, $data['names'][$childrenof] ?? '(Unknown/NI)');
echo str_repeat('=', 80), "\n";

foreach($data['links'][$childrenof] ?? [] as $tgt => $c) {
	printf(
		"%5.1f%%: %-63.63s (%-5.5s)\n",
		100.0 * $c / $data['invokes'][$childrenof],
		$data['names'][$tgt] ?? '(Unknown/NI)',
		$tgt
	);
}
