#!/usr/bin/env php
<?php
/* Author: Romain Dal Maso <artefact2@gmail.com>
 *
 * This program is free software. It comes without any warranty, to the
 * extent permitted by applicable law. You can redistribute it and/or
 * modify it under the terms of the Do What The Fuck You Want To Public
 * License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

namespace HeroesOfLegend;

require __DIR__.'/../inc/root.php';

assert(file_exists($argv[1]));
$data = json_decode(file_get_contents($argv[1]), true);
assert(is_array($data['names']) && is_array($data['links']));

function colorize(string $s): string {
	if($s !== '' && ctype_digit($s[0])) {
		$i = (int)$s[0];
		if($i > 0 && $i < 9) {
			return '/set39/'.$s[0];
		}
	}
	return '/set39/9';
}

echo "digraph \"\" {\n";
echo "rankdir=\"TB\"\n";
echo "graph [pad=.2 nodesep=.2 ranksep=.5 splines=ortho]\n";

foreach($data['names'] as $n => $fn) {
	if(preg_match('%^[0-9]%', $n)) {
		if(preg_match('%[A-Z]$%', $n)) {
			$shape = 'note';
		} else {
			$shape = (isset($data['names'][$n.'A']) || isset($data['names'][$n.'B'])) ? 'folder' : 'box';
		}
	} else {
		$shape = 'doublecircle';
	}
	
	printf(
		"\"%s\" [style=filled fillcolor=\"%s\" label=\"%s\" shape=%s]\n",
		$n, colorize($n), $fn ? $n."\n".$fn : $n, $shape
	);
}

foreach($data['links'] as $src => $l) {
	foreach($l as $tgt => $count) {
		$a = (int)$src;
		$b = (int)$tgt;

		if($a === $b) {
			$weight = 1000;
		} else if($a - ($a % 100) === $b - ($b % 100)) {
			$weight = 100;
		} else if($a < $b) {
			$weight = 10;
		} else {
			$weight = 1;
		}
		
		printf(
			"\"%s\" -> \"%s\" [weight=%d tooltip=\"%s\"]\n",
			$src, $tgt, $count * $weight,
			sprintf("%s: %s -> %s: %s", $src, $data['names'][$src], $tgt, $data['names'][$tgt])
		);
	}
}

echo "}\n";
