#!/usr/bin/env php
<?php
/* Author: Romain Dal Maso <artefact2@gmail.com>
 *
 * This program is free software. It comes without any warranty, to the
 * extent permitted by applicable law. You can redistribute it and/or
 * modify it under the terms of the Do What The Fuck You Want To Public
 * License, Version 2, as published by Sam Hocevar. See
 * http://sam.zoy.org/wtfpl/COPYING for more details. */

namespace HeroesOfLegend;

require __DIR__.'/../inc/root.php';

$data = [];

function merge(array &$base, array $other): void {
	foreach($base as $k => &$bv) {
		if(!isset($other[$k])) continue;
	}

	foreach($other as $k => $ov) {
		if(!isset($base[$k])) {
			$base[$k] = $ov;
			continue;
		}

		if(is_int($ov)) {
			assert(is_int($base[$k]));
			$base[$k] += $ov;
		} else if(is_string($ov)) {
			assert($base[$k] === $ov);
		} else if(is_array($ov)) {
			merge($base[$k], $ov);
		} else {
			assert(false);
		}
	}
}

if($argc === 1) {
	fprintf(STDERR, "Usage: %s <data1.json> <data2.json> …\n", $argv[0]);
	die(1);
}

array_shift($argv);

while($argv !== []) {
	merge(
		$data,
		json_decode(file_get_contents(array_shift($argv)), true)
	);
	fprintf(STDERR, ".");
}

echo json_encode($data);

fprintf(STDERR, "\n");